### ISSUE TITLE
Typo in architecture diagram

### ISSUE THREAD

**Issue by jelliotartz** [input-output-hk/cardano-documentation#105]
There is a small typo in the architecture diagram, specifically in the spelling of GraphQL API Server. See attached image for location.

https://github.com/input-output-hk/cardano-documentation/blob/staging/content/05-explore-cardano/02-cardano-architecture/cardano_components_version_main@2x.png

![9E6B377D-85CC-4A6F-8B91-4BC8A350FB1B](https://user-images.githubusercontent.com/12473119/130711951-31f3bf2d-7430-467b-b579-5df529293814.png)

**Comment by olgahryniuk** [comment]
Thanks for raising this issue! We are on it.

**Comment by olgahryniuk** [comment]
The image is now updated on master: https://github.com/input-output-hk/cardano-documentation/blob/master/content/05-explore-cardano/02-cardano-architecture/01-overview.mdx

**Comment by jelliotartz** [comment]
Awesome, thank you!
