### ISSUE TITLE
cardano-cli: Network.Socket.connect: <socket: 16>: does not exist (No such file or directory)

### ISSUE THREAD

**Issue by the-mercenaries-ltd** [input-output-hk/cardano-documentation#194]
I'm following the https://docs.cardano.org/plutus/Plutus-transactions tutorial

When I run `cardano-cli query tip --mainnet` inside my nix-shell I see the error:
`cardano-cli: Network.Socket.connect: <socket: 16>: does not exist (No such file or directory)`

Here is what I've done previously...

`nix-shell plutus-tutorial.nix`

And then inside the nix-shell I run `cardano-node-mainnet`

What am I missing?

**Comment by olgahryniuk** [comment]
Hello, @jackrobsonalpha! Thank you for raising this issue, we have asked our developer team to take a look at this.

**Comment by luisantonioig** [comment]
Hello @jackrobsonalpha , are you running `nix-shell plutus-tutorial.nix` in the second therminal (where you're running `cardano-cli query tip --mainnet`)? Or just `nix-shell`?
