### ISSUE TITLE
Sitemap has wrong subdomain in links

### ISSUE THREAD

**Issue by katomm** [input-output-hk/cardano-documentation#21]
The sitemap on https://docs.cardano.org/sitemap.xml uses the wrong subdomains for the links.

Example:
```
<loc>https://cardano.org/core-concepts</loc>
```

Should be:
```
<loc>https://docs.cardano.org/core-concepts</loc>
```

**Comment by nahern** [comment]
Hi @martinseanhunt has this been resolved? thanks!

**Comment by martinseanhunt** [comment]
This has been fixed, thanks for the patience on this one!
