### ISSUE TITLE
Cardano-serialization-lib documentation missing

### ISSUE THREAD

**Issue by SebastienGllmt** [input-output-hk/cardano-documentation#23]
Documentation for cardano-serialization-lib was [previously hosted on the old documentation website](https://github.com/Emurgo/cardano-serialization-lib#documentation), but it seems to be no longer included since the new launch. What needs to be done to get it added again?

**Comment by rdlrt** [comment]
@h0rhay @olgahryniuk @martinseanhunt - Could you please address this on priority? The component does have wide userbase, and given that google [crawler links still show results for docs.cardano.org](https://web.archive.org/web/20210410142442/https://docs.cardano.org/projects/cardano-serialization-lib/en/latest/), it would be nice to be able to direct users to final links

**Comment by olgahryniuk** [comment]
Thanks for pointing this out, Sebastien!
We'll add cardano-serialization-lib as part of Cardano components on the new docs site. It will provide an overview of what the library is and redirect users straight into the repository.
See an example here: https://docs.cardano.org/cardano-components/cardano-rosetta 
Creating a ticket for this now.
cc @nahern

**Comment by olgahryniuk** [comment]
@SebastienGllmt @rdlrt 
The PR is ready here for the new section: https://github.com/input-output-hk/cardano-documentation/pull/47
--
The only thing I'd like to note is that we try not to use code/instructions in the overview, as it might change. Thus, best to redirect people to constantly-managed repos. Your doc folder has all the instructions, however, I can't spot the 'building-testing-publishing' bit anywhere. I can see it only in the web archive.
--
Therefore, I suggest merging an overview PR with provided info and links, and also adding a new file within 'cardano-serialization-lib/doc/getting-started/' which will contain building-testing-publishing instructions.
If you agree, let's merge my PR(47) first, and then, I'll create a new PR in your docs folder with those instructions.

**Comment by SebastienGllmt** [comment]
Building & testing is documented at the root of the repository and not in the getting-started folder. You can find it here: https://github.com/Emurgo/cardano-serialization-lib/blob/master/README.rst

**Comment by olgahryniuk** [comment]
Oh, I guess that's why I couldn't find it. Thanks so much for sharing the exact link. I'll add it to our overview and then we'll be all set.
Will share the live link when ready.

**Comment by olgahryniuk** [comment]
@SebastienGllmt, we're now live here:
https://docs.cardano.org/cardano-components/cardano-serialization-lib
Can you please replace the last link in this README file>> https://github.com/Emurgo/cardano-serialization-lib#readme
