### ISSUE TITLE
outdated system requirements for db-sync with node

### ISSUE THREAD

**Issue by gn0tto** [input-output-hk/cardano-documentation#294]
content/05-explore-cardano/02-cardano-architecture/03-cardano-db-sync-best-practices.mdx states the following

```
The system requirements for cardano-db-sync (with both db-sync and the node running on the same machine) are:
{...}
16 Gigabytes of RAM.
{...}
80 Gigabytes or more of disk storage {...}
```

while https://github.com/input-output-hk/cardano-db-sync/blob/master/Readme.md states

```
The system requirements for cardano-db-sync (with both db-sync and the node running on the same machine are:

{...}
32 Gigabytes of RAM or more.
{...}
Ensure that the machine has sufficient IOPS (Input/Output Operations per Second). Ie it should be 60k IOPS or better. Lower IOPS ratings will result in slower sync times and/or falling behind the chain tip.
160 Gigabytes or more of disk storage {...}
```

Both should be in sync (or even better referenced instead of duplicated). I can confirm 16 GB ain't sufficient.

**Comment by olgahryniuk** [comment]
Thanks, @gn0tto for pointing this out! @NeilBurgess42 has now updated the description and also linked to a constantly updated document.
