### ISSUE TITLE
Cardano architecture link leads to 404 on main https://docs.cardano.org/ page

### ISSUE THREAD

**Issue by botondus** [input-output-hk/cardano-documentation#313]
It leads to https://docs.cardano.org/explore-cardano/cardano-architecture/overview
Where is it supposed to point to?

**Comment by olgahryniuk** [comment]
Hello @botondus 
We have recently made several changes to the structure of the Docs site. Cardano architecture is now not a folder but a standalone entry, which sits under 'Explore Cardano' > https://docs.cardano.org/explore-cardano/cardano-architecture
DB Sync components overview and best practices are in the process of being migrated under Cardano Components > Cardano DB Sync.
