### ISSUE TITLE
"Peer-to-peer (P2P) networking" page of Cardano Docs has out of date information

### ISSUE THREAD

**Issue by amichae2** [input-output-hk/cardano-documentation#320]
In the "Peer-to-peer (P2P) networking" page of the Cardano docs it states, "Note: The P2P deployment is currently in testing stages. The team is focused on the delivery of final features for SPOs and the preparation of QuickCheck simulation tests. The full P2P deployment will happen later in 2021. This documentation describes the P2P functionality for information purposes only ahead of this release." I believe this is out of date but do not wan't to create a pull request because this is not my area of expertise.

**Comment by amichae2** [comment]
I'm updating this issue because I found new information. On the "Cardano entropy" page it states, "The Cardano blockchain has transitioned from a federated system run only by 8 nodes in July 2020, to its present state where block production is fully decentralized. The final part of this transition happened on March 31st, 2021 (D=0 Day), a major milestone in Cardano's journey. As of that date, 100% of block production is the responsibility of stake pool operators (SPOs)."

**Comment by olgahryniuk** [comment]
Thanks for raising this issue @amichae2 !
We will update the P2P entry. Currently, the P2P testnet is being actively tested by SPOs to be launched on mainnet soon. This work is ongoing in line with preparation for the Vasil hard fork.
As per the D parameter, this is a bit different topic. D=0, and this means that **block production** is fully decentralized. No single IOG node signs or validates transactions - this is in the hands of the community.
P2P on the other hand allows nodes in the network to communicate with each other directly, and establish connections without **relying** on the topology file, or the connection with the IO relay node. This is not about the D parameter, but about enhanced and automated connections. 
Hope this clarifies some details.
Kind regards
