### ISSUE TITLE
Cardano Architecture overview link leads to 404 page on the Cardano docs page

### ISSUE THREAD

**Issue by ludovico-chiavelli** [input-output-hk/cardano-documentation#328]
If you go to [Cardano Docs](https://docs.cardano.org/) page and scroll down to the *Explore More* section for Cardano architecture the [link](https://docs.cardano.org/explore-cardano/cardano-architecture/overview) leads to a 404 page.

After using the search tool I believe [this link](https://docs.cardano.org/explore-cardano/cardano-architecture) is what it was meant to be.

**Comment by olgahryniuk** [comment]
Thank you for opening a PR to fix this @ludovico-chiavelli! The change is now live.
