### ISSUE TITLE
Consider removing deprecated REST API 

### ISSUE THREAD

**Issue by tmcgilchrist** [input-output-hk/cardano-documentation#337]
The linked REST API project has been deprecated and stopped working after the Alonzo hard-fork. It should not appear in the architecture documentation or list of projects. 

See https://github.com/input-output-hk/cardano-documentation/blob/master/content/05-explore-cardano/02-cardano-architecture.mdx

**Comment by olgahryniuk** [comment]
Thank you for raising this issue, Tim.
I'll delete the link to the repository and will ask the design team to update the graphic. Does it mean that PostgreSQL should include GraphQL and SMASH servers only?

**Comment by tmcgilchrist** [comment]
> Does it mean that PostgreSQL should include GraphQL and SMASH servers only?
Yes that is my understanding. There is no currently supported REST API Server.

**Comment by olgahryniuk** [comment]
Got it, thanks
