### ISSUE TITLE
Minimum ada value requirement is completely outdated

### ISSUE THREAD

**Issue by jonathangenlambda** [input-output-hk/cardano-documentation#357]
When looking at the [Alonzo-](https://github.com/input-output-hk/cardano-ledger/blob/master/eras/alonzo/impl/src/Cardano/Ledger/Alonzo.hs#L115) and [Babbage-era](https://github.com/input-output-hk/cardano-ledger/blob/master/eras/babbage/impl/src/Cardano/Ledger/Babbage/Rules/Utxo.hs#L252) code in cardano-ledger it is more than clear that the documentation which describes the [minimum ada value requirements ](https://docs.cardano.org/native-tokens/minimum-ada-value-requirement) is completely outdated (pre Alonzo!).

Please fix this, it is misguiding and simply wrong (judging by the code).

**Comment by olgahryniuk** [comment]
Thank you for raising this issue. We'll work with the dev team to update this entry.
