### ISSUE TITLE
Testnet faucet ReCAPTCHA is broken

### ISSUE THREAD

**Issue by radflipper** [input-output-hk/cardano-documentation#380]
![image](https://user-images.githubusercontent.com/41245917/185723323-159a7eeb-121e-47e8-a3ce-0651693ffa66.png)

**Comment by olgahryniuk** [comment]
This issue is now resolved, thanks!

**Comment by rtrembecky** [comment]
doesn't seem so
maybe something is being deployed, or #386 fixes it?
https://testnets.cardano.org/cardano-testnet/tools/faucet
<img width="746" alt="image" src="https://user-images.githubusercontent.com/6044119/186142169-8e2c8aae-040c-4441-86bc-ad59b35b861c.png">

**Comment by martinseanhunt** [comment]
This preview deploy is intended to test some new functionality for the faucet internally. The recaptchas haven't been set up to work within the preview deploy context and devops are looking at that for us now. In short, this is behaving as expected.

**Comment by martinseanhunt** [comment]
If you're running this locally we don't allow the use of our recaptchas from localhost for obvious reasons.

**Comment by rtrembecky** [comment]
We're using the old https://testnets.cardano.org/en/testnets/cardano/tools/faucet/ link at https://app.testnet.wingriders.com/welcome and the redirect wasn't working, that's how I found https://testnets.cardano.org/cardano-testnet/tools/faucet as an alternative. But the redirect now correctly gets us to https://docs.cardano.org/cardano-testnet/tools/faucet, so all good, thanks 🙂
