### ISSUE TITLE
Faucet reCapcha error

### ISSUE THREAD

**Issue by hasonhai** [input-output-hk/cardano-documentation#390]
The current Faucet page has an issue with the reCapcha integration.

<img width="845" alt="image" src="https://user-images.githubusercontent.com/1762517/187095280-55e00fb2-2cbc-41d0-8a92-fcef46da4c46.png">

**Comment by olgahryniuk** [comment]
Please access the faucet directly through the Cardano Docs website. There might be an issue with redirects.
https://docs.cardano.org/cardano-testnet/tools/faucet
