### ISSUE TITLE
404 error page on cardano-keys page

### ISSUE THREAD

**Issue by futuristudios** [input-output-hk/cardano-documentation#394]
there's a broken link at https://docs.cardano.org/core-concepts/cardano-keys/ 😅

**Comment by olgahryniuk** [comment]
This section is now hosted under 'Learn' instead of 'Core concepts'. Can you please let me know from which page it links there? We should replace it with:
https://docs.cardano.org/learn/cardano-keys 
Thank you!

**Comment by olgahryniuk** [comment]
We also fixed links to the development repositories. Thanks.
