### ISSUE TITLE
Can not get the tADA!

### ISSUE THREAD

**Issue by sakilhasansaikat** [input-output-hk/cardano-documentation#398]
the reCAPTCA showing : 

ERROR for site owner:
Invalid domain for site key

**Comment by sakilhasansaikat** [comment]
URL : https://testnets.cardano.org/cardano-testnet/tools/faucet

**Comment by olgahryniuk** [comment]
Please access the faucet using this link:
https://docs.cardano.org/cardano-testnet/tools/faucet
