### ISSUE TITLE
Minimum ada value requirement `consequence of the design` partly incorrect

### ISSUE THREAD

**Issue by jonathangenlambda** [input-output-hk/cardano-documentation#399]
The `consequence of the design` section in [Minimum ada value requirement](https://docs.cardano.org/native-tokens/minimum-ada-value-requirement) page contains wrong information:

```
The number of each kind of token in an output does not affect the min-ada-value of the output, but the number of types of tokens contained in an output increases the min-value.
```

According to our own experiments the ``The number of each kind of token in an output does not affect the min-ada-value of the output`` part is plain and simply wrong. Here are the results of a few experiments we ran:

|  ADA | Min-Value  |
|---|---|
|  0  |  961,130  |
|  1  |  961,130  |
|  100  |  965,440  |
|  1,000  |  969,750  |
|  100,000  |  978,370  |
|  10,000,000,000  |  995,610  |
| 10,000,000,000,000,000,000 | 995,610 |

Experiments with custom Tokens showed a similar pattern:
|  XYZ | Min-Value  |
|---|---|
|  1  |  1,124,910  |
|  100  |  1,129,220  |
|  1,000  |  1,133,530  |
|  100,000  |  1,142,150  |

**This clearly shows that when increasing the number of a kind of token, the min-ada-value is affected.**

**Comment by olgahryniuk** [comment]
Thank you for bringing this to our attention! 
We provided some additional details to the explanation.
