### ISSUE TITLE
dark mode 👀 ?

### ISSUE THREAD

**Issue by futuristudios** [input-output-hk/cardano-documentation#402]
the title kinda says it all really… at this point in time it's not just a nice to have as majority of developer resources have made the transition to dark mode - including IDEs!

is there some work happening on this front that's not been made public? or is there some other reason why this hasn't been implemented yet? genuinely curious.

**Comment by olgahryniuk** [comment]
Thanks for raising this issue. We made a feature request and the dark/light mode switch will be implemented soon
