### ISSUE TITLE
Integrate Cardano > Testnet Faucet - Page is being clipped

### ISSUE THREAD

**Issue by blubotsNFT** [input-output-hk/cardano-documentation#414]
When in the Testnet faucet section of the integrate cardano documentation [the Faucet ](https://developers.cardano.org/docs/integrate-cardano/testnet-faucet/) section is clipping the tADA submission process, so much so that the captcha and the address input sections are not selectable. 

![faucet_issue](https://user-images.githubusercontent.com/103647590/194002569-09db9059-92a6-4e12-8a68-facc1a6503f5.png)

**Comment by olgahryniuk** [comment]
Hi @blubotsNFT I suppose this is a screenshot from the Developer Portal (https://developers.cardano.org/docs/integrate-cardano/testnet-faucet/), which is managed by CF, not IOG. Please raise an issue in the Developer Portal GitHub repository.
You can access the faucet via Cardano Docs directly:
https://docs.cardano.org/cardano-testnet/tools/faucet

**Comment by blubotsNFT** [comment]
Ah you're right, my bad, thanks @olgahryniuk!

**Comment by olgahryniuk** [comment]
You're very welcome. Kind regards
