### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by thiago-tsnnst** [input-output-hk/cardano-documentation#423]
This link is not being redirected: https://docs.cardano.org/core-concepts/cardano-keys#gatsby-focus-wrapper
Where I can find a search tool inside the docs page?

**Comment by olgahryniuk** [comment]
Hello @thiago-tsnnst 
Here is the Cardano keys entry: https://docs.cardano.org/learn/cardano-keys
Can you please specify which file includes a broken link to it so I could fix it?
The team are now working on fixing the search engine. Unfortunately, it will take some time
