### ISSUE TITLE
pre-compiled binaries not provided in expected location

### ISSUE THREAD

**Issue by arielelkin** [input-output-hk/cardano-documentation#424]
When following these instructions to download pre-compiled binaries of cardano node and cli:
https://github.com/input-output-hk/cardano-documentation/blob/master/content/06-development-guidelines/01-installing-the-cardano-node.mdx#downloading-pre-compiled-executables

we're instructed to download them from the GitHub releases of cardano-node: https://github.com/input-output-hk/cardano-node/releases 

However, the binaries aren't offered there.

Please clarify where the pre-compiled binaries can be downloaded from.

**Comment by olgahryniuk** [comment]
Hello @arielelkin!
Yes, the link forwards us to the cardano-node releases. Each release offers the Hydra binaries and config files for downloads. Please see:
![image](https://user-images.githubusercontent.com/67585499/199530712-bf3727db-225e-4954-a35b-03bfdc6c8929.png)
Hope this helps

**Comment by olgahryniuk** [comment]
I'd suggest raising this question in the node repository to discuss with the development team. 
Kind regards!
