### ISSUE TITLE
Add copy-able links to headings

### ISSUE THREAD

**Issue by eyeinsky** [input-output-hk/cardano-documentation#426]
Something like github does (the two chain links in front of the heading):
![Screenshot_2022-11-03_17-03-21](https://user-images.githubusercontent.com/9335924/199757457-43b2929a-c941-43e4-b4b1-617e96daa462.png)

This way those exact locatins could be copied and referenced from other places (e.g from cardano.stackexchange.com). The id attributes already seem to be present on the headings and [work](https://docs.cardano.org/native-tokens/getting-started#syntaxofmulti-assetvalues):
![Screenshot_2022-11-03_17-05-25](https://user-images.githubusercontent.com/9335924/199758095-277ed7a2-a042-4e6d-9665-3602aaadf6ea.png)

**Comment by olgahryniuk** [comment]
Hi @eyeinsky 
This functionality is enabled with headings as you pointed out in the example.
The site design does not show the 'chain link', but you can see which headings can be copied here in the side menu:
![image](https://user-images.githubusercontent.com/67585499/199922377-bce3b6a4-5a7c-4d8f-95ce-dd1c7143fb42.png)

**Comment by eyeinsky** [comment]
Right, but chain links would make it much more obvious, as one could copy the link while reading the subsection. The "content" section doesn't scroll along either, so to copy the link you'd need to remember what the heading was, scroll up, copy the link from the content menu.

I.e you're right that copying a link is possible, but it's up to the user to figure out how to do it.

**Comment by olgahryniuk** [comment]
Thank you for your feedback. We'll take this into consideration when/if the site UI/UX will be redesigned. I can't promise any timing, but there is a plan for that.
Kind regards
