### ISSUE TITLE
Adding new smart contract languages to the docs

### ISSUE THREAD

**Issue by nielstron** [input-output-hk/cardano-documentation#461]
In this section of the docs  plutus and Marlowe are mentioned as tools for writing smart contracts:

https://github.com/input-output-hk/cardano-documentation/blob/fb70af93721a1e8966dbc90efc6f1d60a7a8c367/content/02-new-to-cardano/10-what-is-a-smart-contract.mdx

However, new projects like @imperatorlang and @Aiken-lang are emerging and would likely be of interest for anyone planning to build on cardano.

1) Should these projects be listed here at all, given they are community driven and not built by IOHK?
2) Should they be listed as equals or in a "community" / additional references section?
3) Should we wait until they are production ready? Given that they might be production ready by the time a Dev building on them wants to go live

**Comment by olgahryniuk** [comment]
Hello @nielstron! Yes, Plutus and Marlowe are just 2 examples of working with smart contracts on Cardano. I think it will be great to add a paragraph saying that there are more options for working with smart contracts, and one can find out more about community-built tools here:
1. https://docs.cardano.org/plutus/plutus-resources/#plutustooling
2. https://www.essentialcardano.io/article/a-list-of-community-built-developer-tools-on-cardano
I'll add those details soon. Let me know what you think & thanks!

**Comment by nielstron** [comment]
Sounds great! Thanks for considering this :)
