### ISSUE TITLE
Citation doesn't do anything when clicked on the Main Chain Plutus Script page

### ISSUE THREAD

**Issue by amichae2** [input-output-hk/cardano-documentation#475]
It could just be my browser but when I click the 1 at the end of the sentence, "claimTransactionHash of the transaction is NOT included in the distributed set" on the Main Chain Plutus Script page of the Cardano docs it doesn't do anything. Just a small bug but thought I'd let whoever controls this repo know. This is the page: https://docs.cardano.org/cardano-sidechains/sidechain-toolkit/mainchain-plutus-scripts#fn-1 .

**Comment by NeilBurgess42** [comment]
As far as I can see the citation is not lined to anything.
I have deleted the citation. The correction is bundled with changes for ETCM-3500.

**Comment by amichae2** [comment]
Thank you.
