### ISSUE TITLE
Remove info about `bech32` pool ID required format by facuet once ticket in `cardano-world` is implemeted

### ISSUE THREAD

**Issue by ArturWieczorek** [input-output-hk/cardano-documentation#511]
This PR https://github.com/input-output-hk/cardano-documentation/pull/510 updates faucet page with information about required `bech32` format for pool ID when using faucet.

Once this [ticket](https://github.com/input-output-hk/cardano-world/issues/95)  in `cardano-world` repo is implemented facuet will support both formats and additional info about `bech32`format for pool ID can be removed.

**Comment by olgahryniuk** [comment]
@ArturWieczorek, I talked to Filip from the web dev team regarding this issue. Given that nothing's been raised in the last 1.5 years on the referenced opened issue on Jun 20, 2023, we assume everything is functioning correctly. The faucet is a 1-2-1 implementation to what we had before, aside from styling/look and feel changes. 

I believe we can close this issue. Please let me know if anything changes.

Thank you
