### ISSUE TITLE
Invalid documentation links

### ISSUE THREAD

**Issue by amanuelz91** [input-output-hk/cardano-documentation#532]
@ path --> /cardano-testnet/getting-started/

**Under section titled, "Installing the Node":**

- Link titled "cardano-client" links to invalid URL --> https://github.com/input-output-hk/cardano-node/tree/master/cardano-client-demo

**Under section titled, "Configurations":**

-Link titled "Understanding configuration files" links to invalid URL --> https://github.com/input-output-hk/cardano-node/blob/master/doc/getting-started/understanding-config-files.md

-Link titled "Configuring the node using YAML" links to invalid URL --> https://github.com/input-output-hk/cardano-node/blob/master/doc/reference/configuring-a-node-using-yaml.md

**Comment by olgahryniuk** [comment]
Thank you for raising this PR @amanuelz91.
We'll delete the link to the client since all tutorials that build the node also build the client. 
The other two links will be updated shortly.
