### ISSUE TITLE
Wrong links in https://docs.cardano.org/learn/

### ISSUE THREAD

**Issue by steve-anunknown** [input-output-hk/cardano-documentation#549]
There are a couple of wrong links here https://docs.cardano.org/learn/ .

Specifically, https://docs.cardano.org/learn/delegation/ (located here content/03-learn/04-delegation.mdx in the repository) contains at least 2 broken links:

1. "delegation certificate" leads to https://docs.cardano.org/development-guidelines/operating-a-stake-pool/creating-keys-and-certificates#creatinganoperationalcertificate with a "404 not found error". 
2. "multi-sig" leads to https://github.com/input-output-hk/cardano-node/blob/master/doc/reference/simple-scripts.md#multi-signature-scripts with a "404 not found error" once more.

Perhaps (1) is supposed to link to https://docs.cardano.org/operating-a-stake-pool/creating-keys-and-certificates and (2) to https://github.com/input-output-hk/cardano-node/blob/c6b574229f76627a058a7e559599d2fc3f40575d/doc/reference/simple-scripts.md#multisignatures . I can try to fix them, if these are indeed the correct links.

**Comment by olgahryniuk** [comment]
Thank you both for your contributions! I have just updated the multisig link to take a user to the node-wiki, where all node content has migrated. 
We're aware that there are many more broken links, and we will have those fixed in the coming weeks.
