### ISSUE TITLE
Dead link to Cardano node CLI

### ISSUE THREAD

**Issue by m-a-x-s-e-e-l-i-g** [input-output-hk/cardano-documentation#556]
https://github.com/input-output-hk/cardano-documentation/blob/4cba9c43839a10e48080ee1b957d29ed20c63aec/content/11-native-tokens/03-getting-started.mdx#L8

**Comment by olgahryniuk** [comment]
@m-a-x-s-e-e-l-i-g,  thank you for all your PRs to update links. We have also updated multiple links several days ago. It's great to see more contributions as some links might have been missed. Very much appreciated!
