### ISSUE TITLE
Interchange "Distributed systems" and "Decentralized systems" captions on the picture.

### ISSUE THREAD

**Issue by adrian-pusty** [input-output-hk/cardano-documentation#557]
There is this [picture](https://github.com/input-output-hk/cardano-documentation/blob/master/content/02-new-to-cardano/data-storage.png) 
![](https://raw.githubusercontent.com/input-output-hk/cardano-documentation/master/content/02-new-to-cardano/data-storage.png)  
(used [here](https://docs.cardano.org/new-to-cardano/what-is-a-blockchain/))

Shouldn't we interchange "Distributed systems" and "Decentralized systems" captions on this picture?

Excerpts from the [description](https://github.com/input-output-hk/cardano-documentation/blob/master/content/02-new-to-cardano/01-what-is-a-blockchain.mdx) of decentralized system:  
"interconnected, independent nodes and terminals." - we have interconnected nodes on the last picture
"This ensures independence from centralized entities" - only on the last picture we don't have centralized server.

**Comment by olgahryniuk** [comment]
Thank you @adrian-pusty for raising this issue. Indeed, it looks like a mistake, and we have already requested the image update.
