### ISSUE TITLE
Playground Link on homepage goes to 404 (Page not found)

### ISSUE THREAD

**Issue by plaincode** [input-output-hk/cardano-documentation#594]
When visiting cardano.org -> developers -> Marlowe Playground i get a Page not found.

**Comment by olgahryniuk** [comment]
Thanks for raising this issue. The link to the Marlowe Playground is: https://play.marlowe.iohk.io/#/ 
You can find it by navigating through Marlowe Documentation: https://docs.marlowe.iohk.io/docs/introduction

Cardano Docs currently include a general Marlowe overview linking to the Marlowe Docs site. To fix the problem you've mentioned, you can raise an issue on cardano.org. 

Thank you
