### ISSUE TITLE
Clarification on License and Usage Permissions

### ISSUE THREAD

**Issue by katomm** [input-output-hk/cardano-documentation#622]
First of all, thank you for sharing your work on this repository. In particular @olgahryniuk and @nahern have been shipping here for many years. I have found it to be quite valuable and would like to understand more about the licensing and permissions associated with it. Up to today the repository still does not have a license specified. To ensure that I and others can use, distribute, or contribute to this project appropriately, could you please clarify the following:

	1.	License Information: Could you specify which license applies to this repository?
	2.	Permissions Granted: What permissions are granted to users regarding the usage, distribution, 
	and modification of the repo?

Thank you.

**Comment by olgahryniuk** [comment]
Hello, Tommy! Thanks for raising this issue. I'll check with the team and get back with some answers soon.

**Comment by olgahryniuk** [comment]
@katomm, we raised a legal ticket to clarify the points above. 
Regarding permissions, several people from IOG have admin access (web development, dedicated writers), active contributors have write access, and anyone in general can raise an issue or a pull request to suggest changes. 

I'll get back about the license when I hear back from legal. Thanks!

**Comment by olgahryniuk** [comment]
Hello, everyone. Quick update regarding the license. Apache 2.0 works for code repos mostly, so it won't be ideally applicable to the docs site featuring explainers. The legal team is now working on a disclaimer that will put forth that Cardano Docs has an open license for contributors and community collaboration. When ready, we'll publish this on the site potentially as one of the subsections in the 'Contribution guidelines' (in the works) or in any other visible place.

**Comment by olgahryniuk** [comment]
We have received legal approval to use the CC BY 4.0 license, @katomm. I have submitted a request to add it to the site's footer.

**Comment by katomm** [comment]
Thank you for your efforts, Olga and I believe this is a step in the right direction. Problem that I'm seeing is that the basic situation does not change, it rather leads to more confusion. One (not me) could argue that the footer is even misleading in that sense, because the same still applies: Users cannot legally use, copy, or modify the code from the "cardano-documentation"-repository. Doing so without permission could result in legal consequences since no explicit permissions are granted. Users will not have a clear understanding of their rights and responsibilities.

**Comment by olgahryniuk** [comment]
CC BY 4.0 license allows anyone to: 
- share content— copy and redistribute the material in any medium or format for any purpose, even commercially
- adapt — remix, transform, and build upon the material for any purpose, even commercially.

So users can legally use, distribute, and modify content by giving [appropriate credit ](https://creativecommons.org/licenses/by/4.0/#ref-appropriate-credit), providing a link to the license, and [indicating if changes were made ](https://creativecommons.org/licenses/by/4.0/#ref-indicate-changes).

The addition of this license to the whole website is done by [copy-pasting the HTML code into the website's footer](https://wiki.creativecommons.org/wiki/Marking_your_work_with_a_CC_license) (visible on every page). And we will also specify this in the contribution guidelines that are in legal review now too. 

I am not quite sure what else should be done, and I am happy to discuss this further. We mostly have explainers and feature overviews, so CC BY license should work as we agreed before? Please let me know if you have any other suggestions, and we can discuss this further.

Thank you!

**Comment by olgahryniuk** [comment]
The pull request is ready for merging @katomm @KtorZ. Are we happy to go for it? 

https://github.com/input-output-hk/cardano-documentation/pull/630

**Comment by katomm** [comment]
Sorry Olga, while I acknowledge the effort and see how we are walking in the right direction I don't see how this "legal hack" would get my blessing to resolve the issue. 

The repository needs a licence file otherwise it has the implications already mentioned.

I'm keen to hear @KtorZ opinion as he is the expert in these topics.

**Comment by olgahryniuk** [comment]
Looking forward to your suggestions, many thanks!

**Comment by katomm** [comment]
I'm closing this issue in favour of #630
