### ISSUE TITLE
The UI to get test ADA seems broken. 

### ISSUE THREAD

**Issue by zootechdrum** [input-output-hk/cardano-documentation#638]
The URL:
https://docs.cardano.org/cardano-testnets/tools/faucet/

The section:
<img width="912" alt="image" src="https://github.com/user-attachments/assets/79693f62-f87e-41ae-be03-ae6a03cae115">

I click on the dropdown and nothing happens. However when I click on the text "Preview Testnet" I see I get options.

**Comment by olgahryniuk** [comment]
Thanks for raising this issue, @zootechdrum, and apologies for the late response.  I just tried clicking through options, and it seems to work well. Do you still encounter this issue?

**Comment by olgahryniuk** [comment]
I'll close this issue for now, as the faucet is working as expected.
