### ISSUE TITLE
Testnet faucet ReCAPTCHA error

### ISSUE THREAD

**Issue by PolyCrusher** [input-output-hk/cardano-documentation#657]
https://testnets.cardano.org/cardano-testnets/tools/faucet/

The ReCAPTCHA widget response with a error message:

`Error message for website owner:`

`Invalid domain for website key`

**Comment by olgahryniuk** [comment]
@PolyCrusher, the link you've shared is the outdated one (it might be a result of the redirect).
Please use the faucet through this link:
https://docs.cardano.org/cardano-testnets/tools/faucet/
