### ISSUE TITLE
Testnet Faucet isn't displaying the input fields

### ISSUE THREAD

**Issue by fallen-icarus** [input-output-hk/cardano-documentation#677]
Sorry if this isn't the right place for this issue. The docs github link brought me here. 

The [faucet](https://docs.cardano.org/cardano-testnets/tools/faucet) was working a few days ago, but now it doesn't show the fields necessary to actually get tADA. I've tried using both firefox and brave. Both of them don't display the fields anymore. The "Please click here to proceed" link on the page just links to the current page.

**Comment by jnfielding** [comment]
Same, please fix the link as it no longer opens up the submission form.

**Comment by fstoqnov-iohk** [comment]
A fix for this is now live - the adjustment made should ensure we no longer have issues like this in the future

**Comment by primaryobjects** [comment]
Fixed via https://github.com/input-output-hk/cardano-documentation/commit/9b1ab0ab4e28c413f69ae8f258d5df00970ad50b

**Comment by fallen-icarus** [comment]
Thanks! I've tested and confirmed it works again, so I'll close this issue.
