### ISSUE TITLE
Documentation translation to other languages

### ISSUE THREAD

**Issue by alcemirsantos** [input-output-hk/cardano-documentation#90]
First of all, thanks everyone for the amazing job on the Cardano docs!

I could not find any translation branches/issues/pull-requests or the structure to help on this matter. Since the documentation is open to anyone to contribute, I decided to leave here some question on this regard:

1. Is the technologies published in the docs mature enough for translations?
2. Is there already a contribution process defined?
3. If they are not, is it planed only for the 'Basho' phase of the Cardano roadmap? 
4. What is still needed for the translation process take place?

**Comment by nahern** [comment]
Hi @alcemirsantos thank you kindly for your feedback. This new site is better placed to handle auto-translation. I will contact our translation team and investigate if there are any translation plans and let you know! thanks.
